FROM ubuntu
RUN apt update
RUN apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
RUN pip3 install --user --upgrade Cython==0.29.33 virtualenv
RUN pip3 install --user --upgrade buildozer
RUN export PATH=$PATH:~/.local/bin/

USER ${USER}
WORKDIR ${WORK_DIR}
COPY --chown=user:user . ${SRC_DIR}

# installs buildozer and dependencies
RUN pip3 install --user --upgrade Cython==0.29.19 wheel pip virtualenv ${SRC_DIR}

ENTRYPOINT ["buildozer"]
