name: Build apk
on: 
  workflow_dispatch:

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - run: export PATH=$PATH:"~/.local/bin/"
      - run: sudo apt update
      - run: sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
      - run: pip3 install --user --upgrade Cython==0.29.33 virtualenv
      - run: pip3 install --user --upgrade buildozer
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Build with Buildozer
        run: yes | buildozer -v android debug
        id: buildozer

      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: bin/
