name: Build apk
on: 
  workflow_dispatch:

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - run: export PATH=$PATH:"~/.local/bin/"
      - run: pip3 install --user --upgrade buildozer
      - run: sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
      - run: pip3 install --user --upgrade Cython==0.29.33 virtualenv
      - name: Checkout
        uses: actions/checkout@v2

      - run: cd pongpong
      - name: Build with Buildozer
        run: yes | buildozer init
      - run: yes | buildozer -v android debug
        id: buildozer

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
